# render.yaml (New Single Service Version)

services:
  - type: web
    name: pronunciation-pal # A single name for the whole app
    runtime: node
    rootDir: backend # The root is now the backend directory
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: GEMINI_API_KEY
        fromSecret: true
